// <auto-generated />
namespace EventPark.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tout_casse_les_adresses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tout_casse_les_adresses));
        
        string IMigrationMetadata.Id
        {
            get { return "201806080740475_tout_casse_les_adresses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
